spring:
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url连接
    url: jdbc:mysql://39.103.160.187:3306/count?serverTimezone=Asia/Shanghai&userUnicode=true&charsetEncoding=utf8
    # 用户名
    username: root
    # 密码
    password: root